# Generated by Django 3.2.3 on 2021-05-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('dt_str', models.CharField(default='20210529', max_length=8, verbose_name='date')),
                ('dthour_section', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('pop_hhmmss', models.CharField(default='170112', help_text='HH:MM:SS', max_length=8)),
                ('title', models.CharField(max_length=30)),
                ('artist', models.CharField(max_length=24)),
                ('note', models.CharField(max_length=10)),
                ('sysdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
