# Generated by Django 3.2.3 on 2021-05-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='pop_hhmmss',
        ),
        migrations.AddField(
            model_name='collection',
            name='pop_hms',
            field=models.CharField(default='18:33:18', max_length=8),
        ),
        migrations.AlterField(
            model_name='collection',
            name='dt_str',
            field=models.CharField(default='210530', max_length=8, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='dthour_section',
            field=models.CharField(default='053018-', max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collection',
            name='note',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
