# Generated by Django 3.2.3 on 2021-05-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desn', '0002_auto_20210530_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='dthour_section',
            field=models.CharField(default='053019-07', max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collection',
            name='pop_hms',
            field=models.CharField(default='19:07:21', max_length=8),
        ),
    ]
